### ISSUE TITLE
Problem on init // Ubuntu 16.04

### ISSUE THREAD

**Issue by hyphaene** [soutar/hyperterm-summon#23]
Hi,

I'm configuring hyper terminal, and I have a problem when I add you plugin.

I'm on Ubuntu 16.04.

the first output says : 
`Could not register "summon" shortcut (Ctrl+;)`

the second one prints : 
```
Uncaught Exception:
TypeError: app.hide is not a function
    at Object.hideWindows (/home/personne/.hyper_plugins/node_modules/hyperterm-summon/modules/windows.js:33:9)
    at App.app.on (/home/personne/.hyper_plugins/node_modules/hyperterm-summon/modules/setup.js:31:15)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:191:7)
    at BrowserWindow.on (/opt/Hyper/resources/electron.asar/browser/api/browser-window.js:101:9)
    at emitOne (events.js:96:13)
    at BrowserWindow.emit (events.js:188:7)
```

I tried to rebind manually the short by adding : 
```
  summon: {
    hotkey: 'Super+O'
  },

```
on the config file` ~/.hyper.js`, but it doesn't change anything, seems like the option is not parsed at all.

By the way, your documentation mention  `~/.hyperterm.js`, I assume this was the old name of the conf file ?

Cheers.

**Comment by dcalhoun** [comment]
Thanks for the detailed bug report. It is likely the following, which is only accounting for macOS and Windows. https://github.com/soutar/hyperterm-summon/blob/95e92208345ae12061fd0b89c9688b658f980ad8/modules/windows.js#L31-L35

If you'd like to open a PR to add support for Ubuntu, that'd be great! If not, I'll try to take a look at it sometime soon.

P.S. – Yes, the reference to `~/.hyperterm.js` is merely legacy. It just needs to be updated in a PR.

**Comment by hyphaene** [comment]
Hi, 

Of course, I didn't read the source code ...
I'll make a PR !

Cheers
